[workspace]
resolver = "2"
members = [
  "crates/*"
]

[workspace.package]
version = "0.5.0"
description = "Japanese text preprocessor for Text-to-Speech application (OpenJTalk rewrite in rust language)."
license = "BSD-3-Clause"
repository = "https://github.com/jpreprocess/jpreprocess"
keywords = ["tts", "openjtalk", "library"]
categories = ["text-processing"]

rust-version = "1.65.0"

[workspace.dependencies]
jpreprocess-core = { path = "crates/jpreprocess-core" }
jpreprocess-dictionary = { path = "crates/jpreprocess-dictionary" }
jpreprocess-dictionary-builder = { path = "crates/jpreprocess-dictionary-builder" }
jpreprocess-jpcommon = { path = "crates/jpreprocess-jpcommon" }
jpreprocess-naist-jdic = { path = "crates/jpreprocess-naist-jdic" }
jpreprocess-njd = { path = "crates/jpreprocess-njd" }
jpreprocess-window = { path = "crates/jpreprocess-window" }
