[package]
name = "jpreprocess-jpcommon"
version = "0.1.1"
edition = "2021"

description = "Japanese text preprocessor for Text-to-Speech application (OpenJTalk rewrite in rust language)."
license = "BSD-3-Clause"
repository = "https://github.com/jpreprocess/jpreprocess"
keywords = ["tts", "openjtalk", "library"]
categories = ["text-processing"]
documentation = "https://docs.rs/jpreprocess-jpcommon"

[dependencies]
jpreprocess-core = { version = "0.1.1", path="../jpreprocess-core" }
jpreprocess-njd = { version = "0.1.1", path="../jpreprocess-njd" }
