[package]
name = "tests"
edition = "2021"

version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[features]
naist-jdic = ["jpreprocess-mod/naist-jdic"]

[dependencies]
jpreprocess-mod.workspace = true
jpreprocess-mod-core.workspace = true
jpreprocess-mod-dictionary.workspace = true
jpreprocess-mod-njd.workspace = true
jpreprocess-mod-jpcommon.workspace = true

lindera.workspace = true
