[package]
name = "jpreprocess"
version = "0.1.0"
edition = "2021"

license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
naist-jdic=["jpreprocess-naist-jdic/naist-jdic"]

[dependencies]
lindera = { version = "0.23" }
aho-corasick = "0.7"
once_cell = "1.17.0"
anyhow = "1.0.69"
unicode-jp = "0.4.0"

jpreprocess-core = { version = "0.1.0", path="../jpreprocess-core" }

jpreprocess-njd = { version = "0.1.0", path="../jpreprocess-njd" }
jpreprocess-jpcommon = { version = "0.1.0", path="../jpreprocess-jpcommon" }

jpreprocess-dictionary = { version = "0.1.0", path="../jpreprocess-dictionary" }

jpreprocess-naist-jdic = { version = "0.1.0", path="../jpreprocess-naist-jdic", optional = true }
