[package]
name = "jpreprocess"
edition = "2021"

version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

documentation = "https://docs.rs/jpreprocess"

[features]
naist-jdic = ["jpreprocess-naist-jdic/naist-jdic"]
binary = ["clap"]

[[bin]]
name = "jpreprocess"
required-features = ["binary"]

[[bin]]
name = "dict_tools"
required-features = ["binary"]

[dependencies]
lindera-core = { version = "0.27" }
lindera-tokenizer = { version = "0.27" }
lindera-dictionary = { version = "0.27" }

aho-corasick = "1.0"
once_cell = "1.18.0"
anyhow = "1.0.75"
unicode-jp = "0.4.0"

jpreprocess-core = { version = "0.4.0", path="../jpreprocess-core" }
jpreprocess-njd = { version = "0.4.0", path="../jpreprocess-njd" }
jpreprocess-jpcommon = { version = "0.4.0", path="../jpreprocess-jpcommon" }
jpreprocess-dictionary = { version = "0.4.0", path="../jpreprocess-dictionary" }
jpreprocess-dictionary-builder = { version = "0.4.0", path="../jpreprocess-dictionary-builder" }

jpreprocess-naist-jdic = { version = "0.4.0", path="../jpreprocess-naist-jdic", optional = true }

clap = { version = "4.4.2", features = ["derive"], optional = true }
