[package]
name = "jpreprocess-dictionary-builder"
edition = "2021"

version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

documentation = "https://docs.rs/jpreprocess-dictionary-builder"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
byteorder = "1.4.3"
csv = "1.2.2"
env_logger = "0.10.0"
glob = "0.3.1"
log = "0.4.20"
serde = "1.0.188"
yada = "0.5.0"
rayon = "1.7"

lindera-core = { version = "0.27.1" }

jpreprocess-core.workspace = true
jpreprocess-dictionary.workspace = true
