[package]
name = "jpreprocess-core"
version = "0.1.1"
edition = "2021"

description = "Japanese text preprocessor for Text-to-Speech application (OpenJTalk rewrite in rust language)."
license = "BSD-3-Clause"
repository = "https://github.com/jpreprocess/jpreprocess"
keywords = ["tts", "openjtalk", "library"]
categories = ["text-processing"]
documentation = "https://docs.rs/jpreprocess-core"

[dependencies]

thiserror = "1.0.40"
anyhow = "1.0.71"

aho-corasick = "0.7"

lindera-tokenizer = { version = "0.25" }
bincode = "1.3.3"
serde = { version = "1.0.163", features = ["derive"] }
regex = "1.8.3"
once_cell = "1.17.2"
