[package]
name = "jpreprocess-core"
edition = "2021"

version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

documentation = "https://docs.rs/jpreprocess-core"

[dependencies]

thiserror = "1.0.40"
anyhow = "1.0.71"

aho-corasick = "1.0"

lindera-tokenizer = { version = "0.25" }
bincode = "1.3.3"
serde = { version = "1.0.164", features = ["derive"] }
regex = "1.8.4"
once_cell = "1.18.0"
