[package]
name = "jpreprocess-njd"
version = "0.1.1"
edition = "2021"

description = "Japanese text preprocessor for Text-to-Speech application (OpenJTalk rewrite in rust language)."
license = "BSD-3-Clause"
repository = "https://github.com/jpreprocess/jpreprocess"
keywords = ["tts", "openjtalk", "library"]
categories = ["text-processing"]
documentation = "https://docs.rs/jpreprocess-njd"

[dependencies]
phf = { version = "0.11", features = ["macros"] }
lindera-tokenizer = { version = "0.25" }
aho-corasick = "1.0"
once_cell = "1.17.2"

jpreprocess-core = { version = "0.1.1", path="../jpreprocess-core" }
jpreprocess-window = { version = "0.1.1", path="../jpreprocess-window" }
jpreprocess-dictionary = { version = "0.1.1", path="../jpreprocess-dictionary" }
