[package]
name = "jpreprocess-njd"
version = "0.1.0"
edition = "2021"

license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lindera = { version = "0.23" }

jpreprocess-core = { version = "0.1.0", path="../jpreprocess-core" }
jpreprocess-window = { version = "0.1.0", path="../jpreprocess-window" }
jpreprocess-dictionary = { version = "0.1.0", path="../jpreprocess-dictionary" }
