[package]
name = "jpreprocess-dictionary"
edition = "2021"

version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

documentation = "https://docs.rs/jpreprocess-dictionary"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
once_cell = "1.18.0"

lindera-core = { version = "0.26.0" }
lindera-ipadic-builder = { version = "0.26.0" }
serde = { version = "1.0.167" }

jpreprocess-core = { version = "0.2.0", path="../jpreprocess-core" }
