name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  pre-publish-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894
      - name: Setup integration test
        working-directory: crates/jpreprocess/tests
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo jpreprocess/open_jtalk v0.0.5
          chmod +x openjtalk_bin

          gh release download --repo jpreprocess/jpreprocess v0.0.1-rc0
          tar xJvf dictionaries.tar.xz

          rm *.tar.gz *.tar.xz
      - name: Build
        run: cargo build --verbose --all-features
      - name: Run tests
        run: cargo test --verbose --all-features -- --ignored
      - name: Run Clippy
        run: cargo clippy --all-targets

  build-naist-jdic:
    name: Build naist jdic dictionary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894
      - name: Build
        run: cargo build -p jpreprocess-naist-jdic --features=naist-jdic
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: naist-jdic
          path: target/debug/build/jpreprocess-naist-jdic-*

  publish-crates:
    runs-on: ubuntu-latest
    needs: [pre-publish-test]
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3  
      - name: publish
        run: |
          publish_package () {
            VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r ".packages[] | select(.name==\"$1\") | .version")
            VERSIONS=$(curl -s -XGET "https://crates.io/api/v1/crates/$1" | jq -r 'select(.versions != null) | .versions[].num')
            if echo "${VERSIONS}" | grep "${VERSION}" >/dev/null; then
              echo "$1 ${VERSION} has already been published"
            else
              sleep 15
              cargo publish -p "$1" --all-features
            fi
          }

          publish_package "jpreprocess-core"
          sleep 5
          publish_package "jpreprocess-window"
          sleep 5
          publish_package "jpreprocess-dictionary"
          sleep 5
          publish_package "jpreprocess-dictionary-builder"
          sleep 5
          publish_package "jpreprocess-njd"
          sleep 5
          publish_package "jpreprocess-jpcommon"
          sleep 5
          publish_package "jpreprocess-naist-jdic"
          sleep 5
          publish_package "jpreprocess"

  create-release:
    name: Create Release
    needs: [publish-crates, build-naist-jdic]
    runs-on: ubuntu-latest
    steps:
      - name: Download naist-jdic
        uses: actions/download-artifact@v3
        with:
          name: naist-jdic
      - name: Package naist-jdic
        run: |
          mkdir naist-jdic
          cp jpreprocess-naist-jdic-*/out/naist-jdic/* naist-jdic
          tar cvf naist-jdic.tar.gz naist-jdic
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            naist-jdic.tar.gz
