name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4 # v2.6.2

    - name: setup integration test
      working-directory: crates/jpreprocess/tests
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download --repo jpreprocess/open_jtalk v0.0.5
        chmod +x openjtalk_bin

        gh release download --repo jpreprocess/jpreprocess v0.0.1-rc0
        tar xJvf dictionaries.tar.xz

        rm *.tar.gz *.tar.xz

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --include-ignored

    - name: Run Clippy
      run: cargo clippy --all-targets
    - name: Run Format Check
      run: cargo fmt --check

  wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

    - name: Install Rust
      uses: dtolnay/rust-toolchain@f361669954a8ecfc00a3443f35f9ac8e610ffc06 # master
      with:
          toolchain: stable
          targets: wasm32-unknown-unknown

    - name: wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4 # v2.6.2

    - name: Build
      run: |
        cd examples/example-wasm
        wasm-pack build --target nodejs

    - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      with:
        version: 8

    - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: 18
        cache: 'pnpm'
        cache-dependency-path: examples/example-wasm/js/pnpm-lock.yaml

    - name: Test js
      run: |
        cd js
        pnpm i
        pnpm test

  check-msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

    - name: Get MSRV
      id: msrv
      run: echo "msrv=$(cargo metadata --no-deps --format-version=1 | jq -r ".packages[] | select(.name==\"jpreprocess\") | .rust_version")" >> $GITHUB_OUTPUT

    - name: Install Rust
      uses: dtolnay/rust-toolchain@f361669954a8ecfc00a3443f35f9ac8e610ffc06 # master
      with:
          toolchain: ${{ steps.msrv.outputs.msrv }}

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4 # v2.6.2

    - name: Run test
      run: cargo test --verbose
