name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894

    - name: setup integration test
      working-directory: crates/jpreprocess/tests
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download --repo jpreprocess/open_jtalk v0.0.5
        chmod +x openjtalk_bin

        gh release download --repo jpreprocess/jpreprocess v0.0.1-rc0
        tar xJvf dictionaries.tar.xz

        rm *.tar.gz *.tar.xz

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --ignored

    - name: Run Clippy
      run: cargo clippy --all-targets

  check-msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get MSRV
      id: msrv
      run: echo "msrv=$(cargo metadata --no-deps --format-version=1 | jq -r ".packages[] | select(.name==\"jpreprocess\") | .rust_version")" >> $GITHUB_OUTPUT

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ steps.msrv.outputs.msrv }}
          override: true

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894

    - name: Run test
      run: cargo test --verbose
