name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

    - name: setup integration test
      working-directory: crates/jpreprocess/tests
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download --repo jpreprocess/open_jtalk v0.0.5
        chmod +x openjtalk_bin

        gh release download --repo jpreprocess/jpreprocess v0.0.1-rc0
        tar xJvf dictionaries.tar.xz

        rm *.tar.gz *.tar.xz

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --include-ignored

    - name: Run Clippy
      run: cargo clippy --all-targets
    - name: Run Format Check
      run: cargo fmt --check

  wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install Rust
      uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7 # master
      with:
          toolchain: stable
          targets: wasm32-unknown-unknown

    - name: wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

    - name: Build
      run: |
        cd examples/example-wasm
        wasm-pack build --target nodejs

    - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      with:
        version: 8

    - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: examples/example-wasm/js/pnpm-lock.yaml

    - name: Test js
      run: |
        cd examples/example-wasm/js
        pnpm i
        pnpm test

  check-msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Get MSRV
      id: msrv
      run: echo "msrv=$(cargo metadata --no-deps --format-version=1 | jq -r ".packages[] | select(.name==\"jpreprocess\") | .rust_version")" >> $GITHUB_OUTPUT

    - name: Install Rust
      uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7 # master
      with:
          toolchain: ${{ steps.msrv.outputs.msrv }}

    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

    - name: Run test
      run: cargo test --verbose
