[package]
name = "jpreprocess-naist-jdic"
version = "0.1.1"
edition = "2021"

description = "Japanese text preprocessor for Text-to-Speech application (OpenJTalk rewrite in rust language)."
license = "BSD-3-Clause"
repository = "https://github.com/jpreprocess/jpreprocess"
keywords = ["tts", "openjtalk", "library"]
categories = ["text-processing"]
documentation = "https://docs.rs/jpreprocess-naist-jdic"

[features]
naist-jdic = ["encoding", "flate2", "tar", "ureq"]

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
once_cell = "1.12.0"

lindera-core = { version = "0.25.0" }
jpreprocess-core = { version = "0.1.1", path="../jpreprocess-core" }
jpreprocess-dictionary = { version = "0.1.1", path="../jpreprocess-dictionary" }

[build-dependencies]
encoding = { version = "0.2.33", optional = true }
flate2 = { version = "1.0.26", optional = true }
tar = { version = "0.4.38", optional = true }
ureq = { version = "2.6.2", default-features = false, features = ["tls"], optional = true }

lindera-core = { version = "0.25.0" }
jpreprocess-dictionary-builder = { version = "0.1.1", path="../jpreprocess-dictionary-builder" }
