[package]
name = "jpreprocess-naist-jdic"
version = "0.1.0"
edition = "2021"

description = "Japanese text preprocessor for Text-to-Speech application (OpenJTalk rewrite in rust language)."
license = "BSD-3-Clause"
repository = "https://github.com/jpreprocess/jpreprocess"
keywords = ["tts", "openjtalk", "library"]
categories = ["text-processing"]

[features]
naist-jdic=[]

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
once_cell = "1.12.0"

lindera-core = { version = "0.25.0" }
jpreprocess-core = { version = "0.1.0", path="../jpreprocess-core" }
jpreprocess-dictionary = { version = "0.1.0", path="../jpreprocess-dictionary" }

[build-dependencies]
lindera-core = { version = "0.25.0" }
jpreprocess-dictionary-builder = { version = "0.1.0", path="../jpreprocess-dictionary-builder" }
